# Numpy 기초연습문제
-------------

In [1]:
import numpy as np 

### 1. np.zeros를 이용하여 행이 3, 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 a가 되도록 한다.

In [23]:
a = np.zeros((3, 4)) # np.zeros() 함수는 인자로 받는 크기만큼 모든요소가 0인 array를 만든다.
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 2. 위에서 생성한 ndarray a에 대하여, 다중 for 문을 이용하여 아래와 같은 값을 갖도록 초기화하시오.
> array([[ 1.,  2.,  3.,  4.],  
       [ 5.,  6.,  7.,  8.],  
       [ 9., 10., 11., 12.]])  


In [3]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] = i*4 + j + 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [5]:
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num
        num += 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

### 3. 초기화한 a로부터 값 7을 꺼내도록 인덱싱하시오.

In [6]:
a[1, 2]

7.0

### 4. a에서 아래와 같이 둘째 행을 꺼내도록 인덱싱하시오. 단 차원이 유지되어야 한다.  
```array([[5., 6., 7., 8.]])
```

In [7]:
a.shape

(3, 4)

In [9]:
a[[1], :]

array([[5., 6., 7., 8.]])

### 5. a에서 아래와 같이 둘째 열과 셋째 열이 나오도록 인덱싱하시오.

> array([[ 2.,  3.],  
       [ 6.,  7.],  
       [10., 11.]]) 


In [10]:
a[:,[0, 2]]

array([[ 1.,  3.],
       [ 5.,  7.],
       [ 9., 11.]])

### 6. 아래와 같이 a에서 6보다 작거나 같은 값들이 나오도록 불리한인덱싱을 하시오.
 > array([1., 2., 3., 4., 5., 6.])

In [11]:
result = np.asarray([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) if a[i, j] <= 6])
result

array([1., 2., 3., 4., 5., 6.])

In [13]:
a[a <= 6]

array([1., 2., 3., 4., 5., 6.])

### 7. np.random 패키지를 이용하여 0에서 1사이의 값이 무작위로 생성된, 행이 3 열이 4인 ndarray를 생성하시오. 이 때 생성된 ndarray의 이름은 b가 되도록 한다.

In [15]:
b = np.random.random((3, 4))
b

array([[0.59654063, 0.56269833, 0.82068061, 0.16349843],
       [0.37339922, 0.9823258 , 0.67302817, 0.81486791],
       [0.5247087 , 0.70650184, 0.29911485, 0.47696148]])

### 8. a와 b의 요소곱을 하여 c에 저장하시오.

In [17]:
c = a * b
c

array([[0.59654063, 1.12539666, 2.46204183, 0.65399373],
       [1.86699608, 5.89395477, 4.7111972 , 6.51894327],
       [4.72237831, 7.0650184 , 3.2902634 , 5.72353774]])

### 9. b의 전치행렬을 구하여 d에 저장하시오.

In [24]:
d = b.T
d
# 파이썬에서 전치행렬을 구할때 .T / np.transpose / np.swapaxes를 쓸 수 있다.

array([[0.59654063, 0.37339922, 0.5247087 ],
       [0.56269833, 0.9823258 , 0.70650184],
       [0.82068061, 0.67302817, 0.29911485],
       [0.16349843, 0.81486791, 0.47696148]])

In [19]:
d.shape

(4, 3)

### 10. a와 d에 대하여 각 차원의 크기를 출력하시오.

In [20]:
print(a.shape, d.shape)

(3, 4) (4, 3)


### 11. a와 d의 행렬곱을 계산하여 e에 저장하시오.

In [25]:
e = a.dot(d) # numpy.dot 은 numpy.array를 곱할때 사용된다.
e

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 12. e에 대하여 각 열의 합을 계산하시오.

In [22]:
np.sum(e, axis=1)

array([17.19748267, 45.17478655, 73.15209043])